### ISSUE TITLE
 "unot.strictVariable": false 不生效

### ISSUE THREAD

**Issue by firimar** [Simon-He95/unot#11]
插件挺好用的👍

在工作区和全局配置里都设置false，但是还是会自动转换

**Comment by Simon-He95** [comment]
<img width="121" alt="image" src="https://github.com/Simon-He95/unot/assets/57086651/5a628e8a-0d8e-458e-8f2e-e89c8a50af19">
把底部的这个开关关掉试试

**Comment by firimar** [comment]
> <img alt="image" width="121" src="https://private-user-images.githubusercontent.com/57086651/314016686-5a628e8a-0d8e-458e-8f2e-e89c8a50af19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjgwMTEsIm5iZiI6MTcxMDkyNzcxMSwicGF0aCI6Ii81NzA4NjY1MS8zMTQwMTY2ODYtNWE2MjhlOGEtMGQ4ZS00NThlLThmMmUtZTg5YzhhNTBhZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5NDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MmM3N2Y5ZWI1MDkwZWI1NTYzOTVjZTVhYzJhOTU5ZTMyZjI3NjhmODk3ZDM4MmZkOWZiMTY0NDA1NmMxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSbBmB8JM63Q4lP7ybP9iBIwj2h1cqaSBN2s03UxXTM"> 把底部的这个开关关掉试试

关了是不会转换了，但是别的功能也没了， 我只是不想w-10px转成w-[10px], 这个配置不能单独生效吗？

**Comment by Simon-He95** [comment]
> > <img alt="image" width="121" src="https://private-user-images.githubusercontent.com/57086651/314016686-5a628e8a-0d8e-458e-8f2e-e89c8a50af19.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5MjgwMTEsIm5iZiI6MTcxMDkyNzcxMSwicGF0aCI6Ii81NzA4NjY1MS8zMTQwMTY2ODYtNWE2MjhlOGEtMGQ4ZS00NThlLThmMmUtZTg5YzhhNTBhZjE5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIwVDA5NDE1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA1MmM3N2Y5ZWI1MDkwZWI1NTYzOTVjZTVhYzJhOTU5ZTMyZjI3NjhmODk3ZDM4MmZkOWZiMTY0NDA1NmMxZGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.SSbBmB8JM63Q4lP7ybP9iBIwj2h1cqaSBN2s03UxXTM"> 把底部的这个开关关掉试试
> 
> 关了是不会转换了，但是别的功能也没了， 我只是不想w-10px转成w-[10px], 这个配置不能单独生效吗？

是的不能单独生效，w-[10px]，也是work的，回头我可以加一个用户自定义转换的规则在后面，作为一个覆盖，目前是没办法做到单独设置的
