### ISSUE TITLE
class 模式下多条样式转换box-shadow不准确，单条没问题

### ISSUE THREAD

**Issue by firimar** [Simon-He95/unot#13]
<img width="489" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/d423d419-a2b1-433c-a449-6e027586b0e2">

**Comment by Simon-He95** [comment]
@firimar 能提供一条有问题的测试数据吗

**Comment by Simon-He95** [comment]
Due to lack of evidence, I will temporarily close this issue.

**Comment by firimar** [comment]
> Due to lack of evidence



> @firimar 能提供一条有问题的测试数据吗
color: #5b5b5b;
background: #f4f4f4;
