### ISSUE TITLE
background图片路径使用@会出错

### ISSUE THREAD

**Issue by firimar** [Simon-He95/unot#16]
<img width="794" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/4adf54d2-28eb-459e-bf07-55af89bd0478">

 background: url('./../images/line.png') no-repeat 8px 25px; 可以正常转换
background: url('@/assets/images/guide/line.png') no-repeat 8px 25px; 这种不行

**Comment by firimar** [comment]
background: url('./../images/line.png') no-repeat 8px 25px
转换成了
bg-[url(./../images/line.png)] bg-no-repeat bg-8px bg-25px
**bg-8px bg-25px**这种写法似乎不能正常工作

**Comment by Simon-He95** [comment]
fixed in v0.0.72
