### ISSUE TITLE
translate 转换不正确

### ISSUE THREAD

**Issue by firimar** [Simon-He95/unot#17]
<img width="828" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/6b36582e-2fb5-43de-9d7e-6b4bd0e6b297">
<img width="394" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/a2cf3d91-15f2-4715-b222-c6e41d865221">

transform: translate3d(-50%, -50%, 0);
transform: translate(-50%, -50%);

**Comment by Simon-He95** [comment]
has fixed in v0.0.73
