### ISSUE TITLE
格式化有个问题

### ISSUE THREAD

**Issue by weiShaoY** [Simon-He95/unot#19]
比如 原来我写的是 pt-8  开启这个插件后 会改成 pt8,导致看上去没那么清晰, 虽然效果一样,这个怎么配置关闭,另外类似宽高的设置都有这个问题

**Comment by Simon-He95** [comment]
底部栏有一个有状态栏可以关闭

**Comment by Simon-He95** [comment]
<img width="1089" alt="image" src="https://github.com/Simon-He95/unot/assets/57086651/ef788469-d56c-4e0d-9c02-634996a6f803">
