### ISSUE TITLE
Automatic conversion of illegal class names

### ISSUE THREAD

**Issue by lxccc812** [Simon-He95/unot#2]
unocss样式的非法转化导致的样式未能正常生效。
例如 top-0 被转化成 top0 ，left-0 被转化成 left0。

version 
nuxt 3.7.4
@unocss/nuxt 0.56.5
@unocss/eslint-config 0.56.5

tools
UnoT 0.0.49

The illegal conversion of unocss styles causes the styles to fail to take effect normally.
For example, top-0 is converted to top0 and left-0 is converted to left0.

**Comment by Simon-He95** [comment]
It has been fixed in v0.0.50
da5836b2960b2389d76abb135a850aa20c78d588
