### ISSUE TITLE
The shadow format in the class is incorrect in magic mode

### ISSUE THREAD

**Issue by yandixuan** [Simon-He95/unot#20]
shadow-[0px_5px_20px_1px_rgba(181,188,196,0.16)]

https://github.com/Simon-He95/unot/assets/23276822/42588e2e-4633-429e-9780-7d61af5ff6a5

**Comment by yandixuan** [comment]
https://github.com/Simon-He95/unot/blob/79c5588a81750354ada85ce33bc8054e41ef9dc6/src/transform.ts#L81
This line of code affect the transform result

**Comment by Simon-He95** [comment]
v0.0.75 has fixed
