### ISSUE TITLE
类名格式转换问题

### ISSUE THREAD

**Issue by Mr-xue** [Simon-He95/unot#22]
最开始我用的时候，会把 w-18转换成w18，前几天又会把w18转成w-18。
今天用这两种格式都不转换了，写w18 h-18都不会转换了。
我希望吧w18转成w-18该如何设置？

**Comment by Mr-xue** [comment]
貌似是uno-magic的转换功能失效了，重装unoT扩展也不生效

**Comment by Simon-He95** [comment]
> 貌似是uno-magic的转换功能失效了，重装unoT扩展也不生效

试一下v0.0.81版本

**Comment by Mr-xue** [comment]
> > 貌似是uno-magic的转换功能失效了，重装unoT扩展也不生效
> 
> 试一下v0.0.81版本

刚试了还是没生效

**Comment by Mr-xue** [comment]
> > 貌似是uno-magic的转换功能失效了，重装unoT扩展也不生效
> 
> 试一下v0.0.81版本

我看了下你的发

> > > 貌似是uno-magic的转换功能失效了，重装unoT扩展也不生效
> > 
> > 
> > 试一下v0.0.81版本
> 
> 刚试了还是没生效

我看了下你的release记录，貌似0.81版本只改了版本号？

**Comment by Simon-He95** [comment]
因为我本地的是好的，有可能上一个版本忘记打包了

**Comment by Simon-He95** [comment]
<img width="1081" alt="image" src="https://github.com/Simon-He95/unot/assets/57086651/f5271c02-8cd4-451d-9204-9831a3d8a3f2">

**Comment by Mr-xue** [comment]
选项是打开的
<img width="644" alt="image" src="https://github.com/Simon-He95/unot/assets/11676811/5e3fa27a-850a-4741-829e-9226735e63ae">

**Comment by Simon-He95** [comment]
> 选项是打开的 <img alt="image" width="644" src="https://private-user-images.githubusercontent.com/11676811/326231952-5e3fa27a-850a-4741-829e-9226735e63ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODQyNTMsIm5iZiI6MTcxNDI4Mzk1MywicGF0aCI6Ii8xMTY3NjgxMS8zMjYyMzE5NTItNWUzZmEyN2EtODUwYS00NzQxLTgyOWUtOTIyNjczNWU2M2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA1NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDc4ZDcyMGJhZDdkNThiZmY0NDY0ZDk4Y2U3OGYwMzU2Nzk3NjIwOGY0NGJkYTU4ZDRhOTFkOWE4MDVkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mV6PEvHq6-9GedOseXoxuRxm230JaZFITze6Q9k5gUA">

方便提供一个复现demo嘛

**Comment by Mr-xue** [comment]
> > 选项是打开的 <img alt="image" width="644" src="https://private-user-images.githubusercontent.com/11676811/326231952-5e3fa27a-850a-4741-829e-9226735e63ae.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQyODQyNTMsIm5iZiI6MTcxNDI4Mzk1MywicGF0aCI6Ii8xMTY3NjgxMS8zMjYyMzE5NTItNWUzZmEyN2EtODUwYS00NzQxLTgyOWUtOTIyNjczNWU2M2FlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI4VDA1NTkxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY2ZDc4ZDcyMGJhZDdkNThiZmY0NDY0ZDk4Y2U3OGYwMzU2Nzk3NjIwOGY0NGJkYTU4ZDRhOTFkOWE4MDVkZjkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mV6PEvHq6-9GedOseXoxuRxm230JaZFITze6Q9k5gUA">
> 
> 方便提供一个复现demo嘛

这个如何给你提供demo，是录屏么？

**Comment by Simon-He95** [comment]
@Mr-xue 可以给一个简单的git仓库

**Comment by Mr-xue** [comment]
> @Mr-xue 可以给一个简单的git仓库

可以用这个测试下：https://github.com/Mr-xue/test-project.git

**Comment by Simon-He95** [comment]
应该是 vite 插件的预启动，导致的 api 获取路径错误，才没启动插件，你试一下0.0.82版本，应该修复了

**Comment by Mr-xue** [comment]
> 应该是 vite 插件的预启动，导致的 api 获取路径错误，才没启动插件，你试一下0.0.82版本，应该修复了

😭 麻了，还不行~

**Comment by Simon-He95** [comment]
我这边已经没问题了，跑你的测试...，要不卸载重装一下？

**Comment by Mr-xue** [comment]
> 我这边已经没问题了，跑你的测试...，要不卸载重装一下？

发生一件非常奇怪的事情，我刚在测试项目上运行也没问题，但是在我的项目内还是不行。
测试项目就是把我的项目复制了一份，然后把开发的文件删掉，所有unocss、eslint、main.js配置相关文件一模一样。

**Comment by Simon-He95** [comment]
> > 我这边已经没问题了，跑你的测试...，要不卸载重装一下？
> 
> 发生一件非常奇怪的事情，我刚在测试项目上运行也没问题，但是在我的项目内还是不行。 测试项目就是把我的项目复制了一份，然后把开发的文件删掉，所有unocss、eslint、main.js配置相关文件一模一样。

有几点需要你帮忙确认一下：
1: 底部状态栏的 uno-magic 有没有
<img width="94" alt="image" src="https://github.com/Simon-He95/unot/assets/57086651/7a3eba60-c520-4c76-ada5-63f5ae1c43d8">

2: 如果有的话 你检测一下是否只有个别文件存在，保存后插件不生效

**Comment by Mr-xue** [comment]
> > > 我这边已经没问题了，跑你的测试...，要不卸载重装一下？
> > 
> > 
> > 发生一件非常奇怪的事情，我刚在测试项目上运行也没问题，但是在我的项目内还是不行。 测试项目就是把我的项目复制了一份，然后把开发的文件删掉，所有unocss、eslint、main.js配置相关文件一模一样。
> 
> 有几点需要你帮忙确认一下： 1: 底部状态栏的 uno-magic 有没有 <img alt="image" width="94" src="https://private-user-images.githubusercontent.com/57086651/326317135-7a3eba60-c520-4c76-ada5-63f5ae1c43d8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQzNTc3NTksIm5iZiI6MTcxNDM1NzQ1OSwicGF0aCI6Ii81NzA4NjY1MS8zMjYzMTcxMzUtN2EzZWJhNjAtYzUyMC00Yzc2LWFkYTUtNjNmNWFlMWM0M2Q4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDI5VDAyMjQxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBmMDM1ZGRkOTc2MDQ2MGM2MzZmODFhOGIxY2NkMTUyMDZjYmM4NmJkYmEyOWRhNWE2ZjIxNDQyYTA5MjQ5NTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gIXturkegapUlNvdHK1M70PEgEzISpoYWbrAdMknRG0">
> 
> 2: 如果有的话 你检测一下是否只有个别文件存在，保存后插件不生效

终于定位到问题了，我在父容器上用了属性化的border，且用了[rgba(0,0,0,0.06)]这种格式的自定义颜色就会出现问题。
如果不用 中括号包裹是正常的，但是颜色就不生效了。 但是bg用了没问题
```
<div
    class="group relative min-h120 w-full cursor-pointer overflow-hidden rounded-8"
    border="1 solid [rgba(0,0,0,0.06)]"
    bg="[rgba(0,0,0,0.06)]"
  >
  </div>
```

**Comment by Simon-He95** [comment]
没有get到你的意思，我发现`minw`和`minh`的属性忘记加到transform中了

**Comment by Mr-xue** [comment]
> 没有get到你的意思，我发现`minw`和`minh`的属性忘记加到transform中了

你把我上面的那段代码复制到测试项目中，然后在里面再写其他div的样式转换就失效了。
如果把这一行去掉，就没问题了，所以确定是这一行引起的。`border="1 solid [rgba(0,0,0,0.06)]"`

**Comment by Simon-He95** [comment]
v0.0.83 has fixed
Thank you for your help
