### ISSUE TITLE
[Feature] 能否支持转换@apply内的css

### ISSUE THREAD

**Issue by Mr-xue** [Simon-He95/unot#23]
如题，能否支持转换style内@apply书写的的css

**Comment by Simon-He95** [comment]
需要你更细节的描述，比如 `@apply`是什么语法，他是怎么用的，你希望的代码片段和转换后的结果，再考虑是否支持

**Comment by Mr-xue** [comment]
> 需要你更细节的描述，比如 `@apply`是什么语法，他是怎么用的，你希望的代码片段和转换后的结果，再考虑是否支持

就是unocss官方支持的指令转换器：https://unocss.nodejs.cn/transformers/directives

eg：
```css
<style lang="less">
.visitor-show {
  .custom-date {
    @apply w-292 h-40 rounded-8;
    .el-range-separator {
      @apply text-[#666];
    }
  }
}
</style>
```

**Comment by Simon-He95** [comment]
> > 需要你更细节的描述，比如 `@apply`是什么语法，他是怎么用的，你希望的代码片段和转换后的结果，再考虑是否支持
> 
> 就是unocss官方支持的指令转换器：https://unocss.nodejs.cn/transformers/directives
> 
> eg：
> 
> ```css
> <style lang="less">
> .visitor-show {
>   .custom-date {
>     @apply w-292 h-40 rounded-8;
>     .el-range-separator {
>       @apply text-[#666];
>     }
>   }
> }
> </style>
> ```

然后你期望的是什么，`@apply` 中的元素具有保存转换 like `text#fff` -> `text-[#fff]`,你需要将你的期望更好的表达出来:)

**Comment by Mr-xue** [comment]
> > > 需要你更细节的描述，比如 `@apply`是什么语法，他是怎么用的，你希望的代码片段和转换后的结果，再考虑是否支持
> > 
> > 
> > 就是unocss官方支持的指令转换器：https://unocss.nodejs.cn/transformers/directives
> > eg：
> > ```css
> > <style lang="less">
> > .visitor-show {
> >   .custom-date {
> >     @apply w-292 h-40 rounded-8;
> >     .el-range-separator {
> >       @apply text-[#666];
> >     }
> >   }
> > }
> > </style>
> > ```
> 
> 然后你期望的是什么，`@apply` 中的元素具有保存转换 like `text#fff` -> `text-[#fff]`,你需要将你的期望更好的表达出来:)

对，就是启用了uno-magic的转换效果可以应用到apply内部.
