### ISSUE TITLE
在class中有类似w-10px这样的类名,保存时会被格式化成-10px

### ISSUE THREAD

**Issue by lincenying** [Simon-He95/unot#25]
![iShot_2024-05-31_18 24 28](https://github.com/Simon-He95/unot/assets/10840991/2be806de-3e7e-4bdb-b172-6d5ee51e68f2)

p-10px m-10px w-10px h-10px 这种格式的都会被格式化

插件设置:

<img width="636" alt="image" src="https://github.com/Simon-He95/unot/assets/10840991/0df0255f-79fb-44de-9b95-ea10cec94617">

**Comment by Simon-He95** [comment]
卸载重装呢，我这边不能复现

**Comment by lincenying** [comment]
我把设置里几个√去了, 重新勾上, 发现又好了...不知道啥原因...😂
