### ISSUE TITLE
vue中的判断条件也被格式化了

### ISSUE THREAD

**Issue by Mr-xue** [Simon-He95/unot#26]
如图，判断条件也被格式化了，会导致代码逻辑问题。
<img width="627" alt="iShot_2024-06-03_17 24 29" src="https://github.com/Simon-He95/unot/assets/11676811/0087e328-c21b-4dca-afb3-2e146381b429">

**Comment by Simon-He95** [comment]
try to open `strictHyphen`

**Comment by Mr-xue** [comment]
> try to open `strictHyphen`
> 
> <img alt="image" width="990" src="https://private-user-images.githubusercontent.com/57086651/336022935-8a1a514c-fedb-4bb6-a61d-8a6d1f4f70a8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDgzNDMsIm5iZiI6MTcxNzQwODA0MywicGF0aCI6Ii81NzA4NjY1MS8zMzYwMjI5MzUtOGExYTUxNGMtZmVkYi00YmI2LWE2MWQtOGE2ZDFmNGY3MGE4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjAzVDA5NDcyM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVlM2ZmZTNiOWM0ZjBhYTU0NjA3ODM5ZDM4NDMyOWZlNjEzMDE5OTk4NzFhNzhkY2Y3OWZkY2IyNGI3ZmU3ODUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.BwA7oHp9o5Z2v2Acbq-oK_OJxYPE1sLfNY0XOi2oxTk">

这样的话，class内正常的样式也不会转换成h-5这种形式了。
我截图被转换的部分，其实属于判断条件而非样式，这种能否兼容下。

**Comment by Simon-He95** [comment]
0.0.85 has fixed
