### ISSUE TITLE
打开 uno-magic 后 px-10px 变成-10px 了

### ISSUE THREAD

**Issue by firimar** [Simon-He95/unot#27]
目前发现 ml-5px w-20px h-20px px-10px mt-20px  这些都会把前面的属性给整没了

**Comment by Simon-He95** [comment]
I can't reproduce it here.

**Comment by firimar** [comment]
https://github.com/Simon-He95/unot/assets/20078939/d81f7d39-501e-46cf-b910-62a7b1d716bb

我录屏了  设置了保存格式化

**Comment by Simon-He95** [comment]
Can you give me a copy of your current file for testing? I still can't reproduce it here.

**Comment by firimar** [comment]
> Can you give me a copy of your current file for testing? I still can't reproduce it here.

[归档.zip](https://github.com/user-attachments/files/15952907/default.zip)
只是新建个项目然后配置了unocss ， 我刚关闭了所有插件只启用UnoCSS和UnoT ，还是出现了
<img width="445" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/f896481f-4cd1-49ef-a3ef-967cbc531097">
<img width="420" alt="image" src="https://github.com/Simon-He95/unot/assets/20078939/c9ea31e3-8edd-474d-8bb2-febd7fc1b28f">

**Comment by Simon-He95** [comment]
我这边没有问题，请尝试卸载重装，另外检查一下vscode extension中是否存在多个版本的插件，删除后再尝试安装
<img width="423" alt="image" src="https://github.com/Simon-He95/unot/assets/57086651/e3cc650c-d01a-470f-bb1e-9f96b0c3a8f0">

**Comment by firimar** [comment]
确实有两个版本的插件 ，卸载之后，再到extension内删除然后重装也还是不行，实在无法复现就算了，我一般不会开自动转换功能 ，我再找找原因

**Comment by firimar** [comment]
> 我这边没有问题，请尝试卸载重装，另外检查一下vscode extension中是否存在多个版本的插件，删除后再尝试安装 <img alt="image" width="423" src="https://private-user-images.githubusercontent.com/57086651/342294244-e3cc650c-d01a-470f-bb1e-9f96b0c3a8f0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkzMTAwMDEsIm5iZiI6MTcxOTMwOTcwMSwicGF0aCI6Ii81NzA4NjY1MS8zNDIyOTQyNDQtZTNjYzY1MGMtZDAxYS00NzBmLWJiMWUtOWY5NmIwYzNhOGYwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI1VDEwMDE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU3ODlhNmYyY2NlMDYyZmZmMDJiN2U3MGM0MmM5MGE5MDdjNTQxMjg5YjM1N2UyMTgwMDI2YmU4NmFlYjBkMDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.slFYbgmntT-3QA8SLhUKBtNApNDwvPnPyr9KCLfPUMw">

经过排查 发现是 "unot.strictVariable": false 这条设置的原因， 设置了会出现

**Comment by Simon-He95** [comment]
Thank you for the information
