### ISSUE TITLE
可不可以加个: 从剪切板的css, 粘贴为unocss ; 因为一般都用蓝湖 , 这样方便点

### ISSUE THREAD

**Issue by a982246809** [Simon-He95/unot#3]
![image](https://github.com/Simon-He95/unot/assets/56909676/d240250f-7f1b-439f-9118-860d864c48bb)
感觉难度不会很难 , 比如
复制了 
width: 168px;
height: 19px;
使用某个快捷键粘贴为:
w-168px h-19px 
就可以了

**Comment by Simon-He95** [comment]
@a982246809 ，现在可以通过快捷键处理了，需要你在浏览器端复制css，然后在vscode中使用快捷键 `Mac? cmd+alt+v : ctrl+alt+v`
