### ISSUE TITLE
ctrl+alt+v is automatically converted to unocss,  不起作用

### ISSUE THREAD

**Issue by a982246809** [Simon-He95/unot#4]
也搜不到这个命令
![image](https://github.com/Simon-He95/unot/assets/56909676/27b7b980-7862-4ef2-8612-950411ed0fa4)

**Comment by Simon-He95** [comment]
我忘记加这个指令了，快捷键不生效可能是冲突或者按的不对，我这边是能生效的，我现在加一个指令
