### ISSUE TITLE
使用ctrl+alt+v粘贴css代码转unocss,报错command 'UnoT.transform' not found

### ISSUE THREAD

**Issue by hebaq** [Simon-He95/unot#8]
![PixPin_2024-01-29_09-53-46](https://github.com/Simon-He95/unot/assets/61929206/c4394930-1904-448a-ae66-dfd5e1e59ffe)
![PixPin_2024-01-29_09-54-40](https://github.com/Simon-He95/unot/assets/61929206/c9ffe5c9-453d-46bb-bbf5-7be31864fdbe)

**Comment by Simon-He95** [comment]
应该是你当前环境不是unocss，因为插件判断了不是unocss后面的事件就不注册了，所以找不到了，可以再确认一下是否有安装unocss依赖

**Comment by Simon-He95** [comment]
这块的逻辑改了一下，不是unocs环境也能执行命令，但会启动时有一个warning，更新到最新版本即可
